# Writing deployment yaml file 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stories
  template:
    metadata:
      labels:
        app: stories
    spec:
      containers:
      - name: stories
        image: jmcglobal/kub-app:stories-2
        env:  # Hard coding the key value inside the deployment yaml file
          - name: STORY_FOLDER  
            value: 'story'
        # env:        # Using a configmap to store the key value and then reference the configmap
        # - name: STORY_FOLDER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: key-value
        #       key: folder
        volumeMounts:
        - mountPath: /app/story
          name: story-volume
      volumes:
      - name: story-volume
        # emptyDir: {} # This is not advisable, because the volume wont be shared if there is multiple of the same pod
        # hostPath:
        #   path: /data
        #   type: DirectoryOrCreate
        persistentVolumeClaim:
          claimName: pv-claim