apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-api
          image: jmcglobal/kub-dep-user:v2
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://Jmcglobal:Jmcglobal25@cluster1.43icltj.mongodb.net/?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
          volumeMounts:
            - name: efs-volume
              mountPath: /app/users
      volumes:
        - name: efs-volume
          persistentVolumeClaim: 
            claimName: my-volume
